Hot fix: don't display diagnostic plots on mac
freemocap/skellycam pull request #29
Opened 2023-04-03 16:01 UTC by philipqueen

The diagnostic plots that are created after a recording are created in a separate matplotlib GUI, which causes the main skellycam GUI to crash on a Mac. This problem also leads freemocap to crash when recording with webcams on a mac.

This PR adds a system check that turns off the diagnostic plot creation if a Mac is being used. It also displays a warning to Mac users that diagnostic plots aren't being created. This is a hot fix until we are able to move the diagnostic plots into a "diagnostics" widget within qt.

There was also a missing `tqdm` dependency in `requirements.txt` that was added.

2023-04-04 18:56 UTC, jonmatthis requested changes

2023-04-04 18:56 UTC, jonmatthis commented on skellycam/opencv/video_recorder/save_synchronized_videos.py
> +        create_diagnostic_plots_bool = False
This isn't the right way to do this - these if statements and bools just make the logic more confusing

 just set the `show_plots_bool`  below to `false` - that should fix it, right?

2023-04-04 19:02 UTC, philipqueen commented on skellycam/opencv/video_recorder/save_synchronized_videos.py
> +        create_diagnostic_plots_bool = False
I could change it to `if create_diagnostic_plots_bool AND platform.system()== "Darwin":`, but then it makes warning mac users more difficult

2023-04-05 14:49 UTC, jonmatthis commented on skellycam/opencv/video_recorder/save_synchronized_videos.py
> +        create_diagnostic_plots_bool = False
> `if create_diagnostic_plots_bool AND platform.system()== "Darwin":`,

If the logic you're looking for is "Don't do this if its "Darwin" just make that the if statement. 

It can just be somethin glike 


```python

if Darwin or whatever
    return [with whatever needs returning]
    
 [and then put all the stuff that crashes Macs below that if statements, confident that the code will never get there if its running on a Mac]
 
 ```

2023-04-05 14:49 UTC, jonmatthis commented on skellycam/opencv/video_recorder/save_synchronized_videos.py
> +        create_diagnostic_plots_bool = False
(note -  I didn't check the code again when writing these comments, so apologies if it doesn't match whats in there)

2023-04-05 15:18 UTC, philipqueen commented on skellycam/opencv/video_recorder/save_synchronized_videos.py
> +        create_diagnostic_plots_bool = False
Just committed a simpler logic per our conversation

2023-04-05 15:22 UTC, jonmatthis commented on skellycam/opencv/video_recorder/save_synchronized_videos.py
> +        logger.info("Darwin (Mac) system detected, diagnostic plots for webcams will not be displayed")
```suggestion
        logger.info("Non-Windows system detected, diagnostic plots for webcams will not be displayed")
```

2023-04-05 15:23 UTC, jonmatthis approved these changes

2023-04-05 15:23 UTC, merged